export const experienceConfig = {
  motion: {
    enabled: false,
    revealPreset: "clip-rise",
    controlFeedbackMs: 160,
    chapterTransitionMs: 620,
  },
  particles: {
    enabled: true,
    initialScene: "scattered-field",
    lazyLoadDelayMs: 120,
    ambientMotion: {
      drift: 0.24,
      rotationX: 0.055,
      rotationY: 0.38,
      rotationZ: 0.025,
      floatY: 0.07,
      floatZ: 0.1,
      fullRotationSeconds: 42,
      pointerTravel: 0.16,
      pointerTilt: 0.1,
      scrollRotationLimit: 0.26,
      scrollRotationReturn: 1.1,
      objectLooseness: 0.075,
      electronDrift: 0.056,
      electronSpeed: 0.34,
      transitionSpread: 0.88,
    },
    surfaceField: {
      colourCycleSeconds: 14,
      primaryScale: 1.08,
      secondaryScale: 1.86,
      residualMix: 0.16,
      densityScale: 0.82,
      densityContrast: 0.62,
      densityCycleSeconds: 24,
      mobileDensityFloor: { dark: 0.5, light: 0.62 },
    },
    ambientField: {
      counts: {
        home: 84,
        contact: 76,
        services: 84,
        works: 138,
      },
      frameRate: { desktop: 45, mobile: 30 },
      pixelRatioCap: 1.25,
      travelX: { min: 28, range: 72 },
      travelY: { min: 34, range: 82 },
    },
    aboutHead: {
      mobilePointLimit: 5600,
      pointSize: 9.2,
      scale: 0.88,
      densityFloor: 0.52,
      rotation: {
        resting: { x: 0.03, y: -0.2 },
        scroll: { x: -0.22, y: 1.3 },
        pointer: { x: 0.11, y: 0.14 },
        idle: { x: 0.018, y: 0.055 },
      },
      electron: {
        rate: { min: 0.24, range: 0.72 },
        amplitude: { min: 0.032, range: 0.046 },
      },
    },
    servicesOrb: {
      count: 780,
      densityFloor: 0.56,
      rotation: { start: -0.3, end: -1.1, idleRange: 0.14 },
      scale: { start: 0.82, end: 1.08 },
      pointerTilt: { x: 0.16, y: 0.18 },
      electronAmplitude: { min: 0.016, range: 0.038 },
      maxFrameRate: 45,
      pixelRatioCap: 1.25,
    },
    heroModel: {
      url: "/models/webine-logo-particle.glb",
      targetSize: 5.2,
      fit: "largest",
      rotationDegrees: [0, 0, 0],
      offset: [0, 0, 0],
      localScale: [1, 1, 2.5],
      seed: 20260715,
    },
    closingModel: {
      url: "/models/colony-planet-particle.glb",
      targetSize: 4.8,
      fit: "largest",
      rotationDegrees: [58, -22, 0],
      offset: [0, 0, 0],
      localScale: [1, 1, 1],
      ambientRotationScale: 0.42,
      seed: 20260714,
    },
    desktop: {
      minWidth: 1024,
      count: 6000,
      ambientRatio: 0.045,
      pointSize: 3.2,
      pixelRatioCap: 1.5,
      objectScale: 1,
      maxFrameRate: 60,
      measurementSettleMs: 1200,
    },
    tablet: {
      count: 1800,
      ambientRatio: 0.035,
      pointSize: 4.2,
      pixelRatioCap: 1.25,
      objectScale: 1.22,
      maxFrameRate: 60,
      measurementSettleMs: 1200,
    },
    mobile: {
      maxWidth: 599,
      count: 2200,
      renderRatio: 1,
      pointSize: 1.69,
      objectLooseness: 0.5,
      electronDrift: 5.2,
      maxFrameRate: 30,
      measurementSettleMs: 90,
    },
  },
  smoothScroll: {
    enabled: true,
    lerp: 0.075,
    smoothWheel: true,
    wheelMultiplier: 0.92,
    maxWheelDelta: 84,
    syncTouch: true,
    syncTouchLerp: 0.075,
    touchInertiaExponent: 1.7,
    touchMultiplier: 1,
    overscroll: true,
  },
  signalGrid: {
    enabled: true,
    sections: ["hero", "closing-cta"],
    desktopCellSize: 48,
    mobileCellSize: 32,
  },
  pageTransitions: {
    enabled: false,
    preset: "folded-panel-wipe",
    durationMs: 600,
  },
} as const;

export const particleSceneConfig = {
  hero: {
    id: "hero",
    startTarget: "scattered-field",
    endTarget: "folded-webine",
    theme: "dark",
    motion: {
      formation: { enterViewportY: 1, formedViewportY: 0.5 },
      dispersion: { startViewportY: 0, completeViewportY: -0.34 },
    },
    desktop: { anchorX: 0.75, anchorY: 0.46, scale: 0.82 },
    tablet: { anchorX: 0.76, anchorY: 0.46, scale: 0.46 },
    mobile: { anchorX: 0.68, anchorY: 0.42, scale: 0.34 },
  },
  reach: {
    id: "reach",
    theme: "light",
    motion: {
      formation: { enterViewportY: 0.96, formedViewportY: 0.5 },
      dispersion: { startViewportY: 0, completeViewportY: -0.3 },
    },
    desktop: { anchorX: 0.8, anchorY: 0.2, scale: 0.86 },
    tablet: { anchorX: 0.86, anchorY: 0.2, scale: 0.62 },
    mobile: { anchorX: 0.68, anchorY: 0.22, scale: 0.3 },
  },
  interlude: {
    id: "interlude",
    theme: "light",
    motion: {
      formation: { enterViewportY: 0.96, formedViewportY: 0.67 },
      dispersion: { startViewportY: 0, completeViewportY: -0.28 },
    },
    desktop: { anchorX: 0.8, anchorY: 0.9, scale: 0.78 },
    tablet: { anchorX: 0.84, anchorY: 0.9, scale: 0.58 },
    mobile: { anchorX: 0.66, anchorY: 0.8, scale: 0.3 },
  },
  process: {
    id: "process",
    theme: "dark",
    desktop: { scale: 0.82 },
    tablet: { scale: 0.68 },
    mobile: { scale: 0.54 },
  },
  closing: {
    id: "closing",
    theme: "dark",
    motion: {
      formation: { enterViewportY: 1.28, formedViewportY: 0.62 },
      dispersion: { startViewportY: 0, completeViewportY: -0.28 },
    },
    desktop: { anchorX: 0.76, anchorY: 0.5, scale: 1.06 },
    tablet: { anchorX: 0.76, anchorY: 0.5, scale: 0.72 },
    mobile: { anchorX: 0.68, anchorY: 0.76, scale: 0.34 },
  },
} as const;

export const experienceMode = Object.values(experienceConfig).some(
  (feature) => feature.enabled,
)
  ? "enhanced"
  : "static";
