export const particleObjectScaleConfig = {
  home: {
    renderer: { desktop: 1, tablet: 1.22 },
    hero: { desktop: 1.4, tablet: 0.52, mobile: 0.38 },
    reach: { desktop: 0.86, tablet: 0.62, mobile: 0.3 },
    interlude: { desktop: 0.78, tablet: 0.58, mobile: 0.3 },
    process: { desktop: 0.82, tablet: 0.68, mobile: 0.54 },
    closing: { desktop: 1.06, tablet: 0.72, mobile: 0.34 },
  },
  aboutHead: { desktop: 0.88, mobile: 0.88 },
  services: {
    mobileMultiplier: 0.52,
    "website-design": 1.65,
    "website-redesign": 1.3,
    "landing-pages": 2.7,
    "branding-support": 1.62,
    "seo-foundations": 1.72,
    "website-care": 1.72,
  },
} as const;

export const experienceConfig = {
  pageLoader: {
    enabled: true,
    minimumVisibleMs: 280,
    completionHoldMs: 80,
    exitDurationMs: 260,
    maximumWaitMs: 7000,
    assetSettleMs: 80,
  },
  motion: {
    enabled: false,
    revealPreset: "clip-rise",
    controlFeedbackMs: 160,
    chapterTransitionMs: 620,
  },
  particles: {
    enabled: true,
    initialScene: "scattered-field",
    lazyLoadDelayMs: 120,
    glow: {
      haloScale: 2.45,
      haloAlpha: 0.16,
      lightHaloScale: 0.72,
      lightHaloAlpha: 0.065,
      coreScale: 0.78,
      shaderSpriteScale: 3.2,
      shaderCoreStart: 0.065,
      shaderCoreEnd: 0.13,
      shaderHaloStart: 0.36,
      objectPointSize: { desktop: 3.2, mobile: 1.69 },
      perspectiveScale: { desktop: 7, mobile: 5 },
    },
    ambientMotion: {
      drift: 0.24,
      rotationX: 0.055,
      rotationY: 0.38,
      rotationZ: 0.025,
      floatY: 0.07,
      floatZ: 0.1,
      fullRotationSeconds: 42,
      pointerTravel: 0.16,
      pointerTilt: 0.1,
      pointerBulge: {
        // Screen-space area affected by the cursor. Larger values widen the bulge.
        screenRadius: 0.5,
        // Distance the selected particles move towards the camera.
        depth: 0.35,
        // Extra point-size growth at the centre of the bulge.
        pointScale: 0.22,
        // Higher values keep the effect tighter around the cursor.
        falloffPower: 1.45,
        // Overall multiplier for the complete bulge response.
        strength: 1,
      },
      scrollRotationLimit: 0.26,
      scrollRotationReturn: 1.1,
      objectLooseness: 0.075,
      electronDrift: 0.056,
      electronSpeed: 0.34,
      transitionSpread: 0.88,
    },
    surfaceField: {
      colourCycleSeconds: 14,
      primaryScale: 1.08,
      secondaryScale: 1.86,
      residualMix: 0.16,
      densityScale: 0.82,
      densityContrast: 0.62,
      densityCycleSeconds: 24,
      mobileDensityFloor: { dark: 0.5, light: 0.62 },
    },
    ambientField: {
      counts: {
        home: 84,
        contact: 76,
        services: 84,
        timeline: 96,
        works: 138,
      },
      frameRate: { desktop: 45, mobile: 30 },
      pixelRatioCap: 1.25,
      travelX: { min: 28, range: 72 },
      travelY: { min: 34, range: 82 },
    },
    aboutHead: {
      mobilePointLimit: 5600,
      densityFloor: 0.52,
      sequence: {
        scrollScreens: { desktop: 2.4, mobile: 2.1 },
        scrub: { desktop: 1.1, mobile: 0.78 },
        frame: {
          desktop: { scaleX: 0.965, scaleY: 0.94 },
          mobile: { scaleX: 0.94, scaleY: 0.93 },
        },
      },
      rotation: {
        resting: { x: 0.03, y: -0.2 },
        scroll: { x: -0.14, y: 0.84 },
        idle: { x: 0.018, y: 0.055 },
      },
      electron: {
        rate: { min: 0.24, range: 0.72 },
        amplitude: { min: 0.032, range: 0.046 },
      },
    },
    aboutPortrait: {
      sequence: {
        outlineDurationSeconds: 1.8,
        completedOutlineHoldSeconds: 0.4,
        particleFadeSeconds: 0.8,
        imageRevealSeconds: 0.9,
        imageRevealDelayAfterParticleFadeStartsSeconds: 0.0,
      },
      motion: {
        settledFlow: { desktop: 0.18, mobile: 0.58 },
      },
      waterRipple: {
        strength: 0.5,
        radius: 0.075,
        damping: 0.975,
        propagation: 0.235,
        speedThreshold: 0.14,
        fullStrengthSpeed: 1.55,
        edgeDisplacement: 0.01,
        colorRevealRadius: 0.16,
        colorRevealDecay: 3.2,
        colorRevealShrink: 0.18,
      },
    },
    servicesMorph: {
      count: { desktop: 3600, mobile: 2200 },
      transitionSeconds: 1.05,
      transitionSpread: 1.15,
      mobileScale: particleObjectScaleConfig.services.mobileMultiplier,
      anchor: {
        // Moves the complete Services particle stage. Negative Y places it lower.
        desktop: { x: -1.32, y: -0.22, z: 0 },
        mobile: { x: 0, y: -0.06, z: 0 },
      },
      maxFrameRate: { desktop: 42, mobile: 30 },
      pixelRatioCap: 1.25,
      electronAmplitude: 0.032,
      mobiusRunner: {
        pointCount: 96,
        sphereRadius: 0.055,
        pathCentreX: 0.117,
        pathRadius: 0.81,
        speed: 0.62,
      },
      // Per-model visual-centre correction. Positive X moves right, Y moves up and Z moves closer.
      models: [
        {
          key: "website-design",
          url: "/models/services/service-globe-points.glb",
          scale: particleObjectScaleConfig.services["website-design"],
          rotation: { x: 0.02, restingY: -0.2 },
          centreOffset: { x: 0, y: 0, z: 0 },
        },
        {
          key: "website-redesign",
          url: "/models/services/service-redesign-points.glb",
          scale: particleObjectScaleConfig.services["website-redesign"],
          rotation: { x: -0.18, restingY: 3.8416 },
          centreOffset: { x: 0, y: 0, z: 0 },
        },
        {
          key: "landing-pages",
          url: "/models/services/service-landing-page-points.glb",
          scale: particleObjectScaleConfig.services["landing-pages"],
          rotation: { x: 0.24, restingY: 3.0 },
          // The aircraft's visual mass sits low, so this brings its composition point up.
          centreOffset: { x: 0, y: 0.14, z: 0 },
        },
        {
          key: "branding-support",
          url: "/models/services/service-branding-points.glb",
          scale: particleObjectScaleConfig.services["branding-support"],
          rotation: { x: 0.16, restingY: -0.18 },
          centreOffset: { x: 0, y: 0, z: 0 },
        },
        {
          key: "seo-foundations",
          url: "/models/services/service-seo-points.glb",
          scale: particleObjectScaleConfig.services["seo-foundations"],
          rotation: { x: -0.05, restingY: -0.12 },
          centreOffset: { x: 0, y: 0, z: 0 },
        },
        {
          key: "website-care",
          url: "/models/services/service-care-points.glb",
          scale: particleObjectScaleConfig.services["website-care"],
          rotation: { x: -0.38, restingY: -0.16 },
          centreOffset: { x: 0, y: 0, z: 0 },
        },
      ],
    },
    heroModel: {
      url: "/models/webine-logo-particle.glb",
      targetSize: 5.2,
      fit: "largest",
      rotationDegrees: [0, 0, 0],
      offset: [0, 0, 0],
      localScale: [1, 1, 2.5],
      seed: 20260715,
    },
    reachModel: {
      url: "/models/reach-rings-particle.glb",
      targetSize: 5.18,
      fit: "largest",
      rotationDegrees: [0, -30, 0],
      offset: [0, 0, 0],
      localScale: [1, 1, 1],
      seed: 20260719,
    },
    interludeObject: {
      type: "elliptical-torus-bands",
      bandCount: 3,
      radiusX: { base: 1.32, step: 0.48 },
      radiusY: { base: 0.92, step: 0.32 },
      tubeRadius: 0.2,
      rotationDegrees: [0, 150, 0],
    },
    closingModel: {
      url: "/models/colony-planet-particle.glb",
      targetSize: 4.8,
      fit: "largest",
      rotationDegrees: [58, -22, 0],
      offset: [0, 0, 0],
      localScale: [1, 1, 1],
      ambientRotationScale: 0.42,
      seed: 20260714,
    },
    desktop: {
      minWidth: 1024,
      count: 2800,
      ambientRatio: 0.045,
      pointSize: 3.2,
      pixelRatioCap: 1,
      objectScale: particleObjectScaleConfig.home.renderer.desktop,
      maxFrameRate: 36,
      measurementSettleMs: 420,
    },
    tablet: {
      count: 1800,
      ambientRatio: 0.035,
      pointSize: 3.2,
      pixelRatioCap: 1.25,
      objectScale: particleObjectScaleConfig.home.renderer.tablet,
      maxFrameRate: 60,
      measurementSettleMs: 1200,
    },
    mobile: {
      maxWidth: 599,
      count: 2200,
      renderRatio: 1,
      pointSize: 1.69,
      objectLooseness: 0.5,
      electronDrift: 5.2,
      maxFrameRate: 30,
      measurementSettleMs: 90,
    },
  },
  smoothScroll: {
    enabled: true,
    lerp: 0.075,
    smoothWheel: true,
    wheelMultiplier: 0.92,
    maxWheelDelta: 84,
    syncTouch: true,
    syncTouchLerp: 0.07,
    touchInertiaExponent: 1.7,
    touchMultiplier: 1,
    overscroll: true,
  },
  signalGrid: {
    enabled: true,
    sections: ["hero"],
    desktopCellSize: 48,
    mobileCellSize: 32,
  },
} as const;

export const particleSceneConfig = {
  hero: {
    id: "hero",
    startTarget: "scattered-field",
    endTarget: "folded-webine",
    theme: "dark",
    motion: {
      formation: { enterViewportY: 1, formedViewportY: 0.5 },
      dispersion: { startViewportY: 0.4, completeViewportY: -0.34 },
    },
    desktop: { anchorX: 0.70, anchorY: 0.50, scale: particleObjectScaleConfig.home.hero.desktop },
    tablet: { anchorX: 0.76, anchorY: 0.46, scale: particleObjectScaleConfig.home.hero.tablet },
    mobile: { anchorX: 0.68, anchorY: 0.42, scale: particleObjectScaleConfig.home.hero.mobile },
  },
  reach: {
    id: "reach",
    theme: "light",
    motion: {
      formation: { enterViewportY: 0.96, formedViewportY: 0.5 },
      dispersion: { startViewportY: 0, completeViewportY: -0.3 },
    },
    desktop: { anchorX: 0.8, anchorY: 0.2, scale: particleObjectScaleConfig.home.reach.desktop },
    tablet: { anchorX: 0.86, anchorY: 0.2, scale: particleObjectScaleConfig.home.reach.tablet },
    mobile: { anchorX: 0.68, anchorY: 0.22, scale: particleObjectScaleConfig.home.reach.mobile },
  },
  interlude: {
    id: "interlude",
    theme: "light",
    motion: {
      formation: { enterViewportY: 0.96, formedViewportY: 0.67 },
      dispersion: { startViewportY: 0, completeViewportY: -0.28 },
    },
    desktop: { anchorX: 0.8, anchorY: 0.9, scale: particleObjectScaleConfig.home.interlude.desktop },
    tablet: { anchorX: 0.84, anchorY: 0.9, scale: particleObjectScaleConfig.home.interlude.tablet },
    mobile: { anchorX: 0.66, anchorY: 0.8, scale: particleObjectScaleConfig.home.interlude.mobile },
  },
  process: {
    id: "process",
    theme: "dark",
    desktop: { scale: particleObjectScaleConfig.home.process.desktop },
    tablet: { scale: particleObjectScaleConfig.home.process.tablet },
    mobile: { scale: particleObjectScaleConfig.home.process.mobile },
  },
  closing: {
    id: "closing",
    theme: "dark",
    motion: {
      formation: { enterViewportY: 1.2, formedViewportY: 0.62 },
      mobileFormation: { enterViewportY: 1.5, formedViewportY: -1 },
      dispersion: { startViewportY: 0, completeViewportY: -0.28 },
    },
    desktop: { anchorX: 0.76, anchorY: 0.5, scale: particleObjectScaleConfig.home.closing.desktop },
    tablet: { anchorX: 0.76, anchorY: 0.5, scale: particleObjectScaleConfig.home.closing.tablet },
    mobile: { anchorX: 0.68, anchorY: 0.76, scale: particleObjectScaleConfig.home.closing.mobile },
  },
} as const;

export const experienceMode = Object.values(experienceConfig).some(
  (feature) => feature.enabled,
)
  ? "enhanced"
  : "static";
